apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: docker-registry-checker
build:
  artifacts:
    - image: docker-registry-checker
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - src/*
          - lib/*
          - k8s-inventory.py
          - registry-checker.py
  local: {}

manifests:
  kustomize:
    paths:
      - kustomize/base
  
deploy:
  kubectl:
    defaultNamespace: ops-staging

profiles:
- name: dev
  activation:
    - command: dev
      
- name: prod
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/prod
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-production
