apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: docker-registry-checker
build:
  artifacts:
    - image: docker-registry-checker
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - src/*
        - lib/*
        - k8s-inventory.py
        - registry-checker.py
  local: {}

manifests:
  kustomize:
    paths:
      - kustomize/base
  
#  rawYaml:
#    - kustomize/base/01-ServiceAccount.yaml
#    - kustomize/base/02-ClusterRole.yaml
#    - kustomize/base/03-ClusterRoleBinding.yaml
#    - kustomize/base/04-Deployment.yaml

deploy:
  kubectl:
    defaultNamespace: ops-staging
    flags:
      global:
        - "-n"
        - "ops-staging"

profiles:
- name: dev
  activation:
    - command: dev
      
- name: prod
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/prod
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-production
    - op: replace
      path: /deploy/kubectl/flags/global
      value:
        - "-n"
        - "ops-production"

