# Defaults here
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: docker-registry-checker
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: docker-registry-checker
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - src/*
          - lib/*
          - k8s-inventory.py
          - registry-checker.py
  local: {}

manifests:
  kustomize:
    paths:
      - kustomize/stage
  
deploy:
  kubectl:
    defaultNamespace: ops-staging


# Changes according to profile here

profiles:
- name: dev
  activation:
    - command: dev

- name: stage
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/stage
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-staging
    - op: replace
      path: /build/tagPolicy
      value:
        gitCommit: {}
      
- name: prod
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/prod
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-production
    - op: replace
      path: /build/tagPolicy
      value:
        gitCommit: {}
