# Defaults here
apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: docker-registry-checker
build:
# Setting this forces docker image rebuild on every change which is
# often a bit much.  But sometimes it's too hard to make skaffold rebuild
# the image.
#  tagPolicy:
#    inputDigest: {}
  artifacts:
    - image: docker-registry-checker
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - app/*
          - "*.py"
          - "*.sh"
  local: {}

manifests:
  kustomize:
    paths:
      - kustomize/dev
  
deploy:
  kubectl:
    defaultNamespace: ops-dev


# Changes according to profile here

profiles:
- name: dev
  activation:
    - command: dev

- name: staging
  activation:
    - command: run
    - command: delete
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/staging
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-staging
      
- name: prod
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/prod
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-production
    - op: add
      path: /build/tagPolicy
      value:
        # The Makefile forces git commit before deploy
        gitCommit: {}

- name: vglabprod
  patches:
    - op: replace
      path: /manifests/kustomize/paths/0
      value: kustomize/vglabprod
    - op: replace
      path: /deploy/kubectl/defaultNamespace
      value: ops-production
    - op: add
      path: /build/tagPolicy
      value:
        gitCommit: {}
