apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: docker-registry-checker-staging
  name: crb-docker-registry-checker

subjects:
- kind: "ServiceAccount"
  name: "sa-docker-registry-checker-staging"
  namespace: ops-staging
roleRef:
  name: "cr-docker-registry-checker-staging"

