apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-checker
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-checker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: docker-registry-checker
    spec:
      volumes:
        - name: secret-volume
          secret:
            # This name is defined in base/kustomization.yaml
            secretName: test-secrets

      serviceAccountName: sa-docker-registry-checker-stage
      containers:
      - name: docker-registry-checker
        image: docker-registry-checker
        resources: {}
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 60
        volumeMounts:
          - name: secret-volume
            readOnly: true
            mountPath: /etc/secrets
status: {}
