apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry-checker
  template:
    metadata:
      labels:
        app: docker-registry-checker
    spec:
      serviceAccountName: sa-docker-registry-checker-dev
      containers:
      - name: docker-registry-checker
        image: docker-registry-checker
        env:
          - name: FOO
            value: BAR
        envFrom:
          - secretRef:
              name: docker-registry-checker-dev
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 60

