apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-registry-checker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-registry-checker
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-registry-checker
subjects:
- kind: ServiceAccount
  name: docker-registry-checker
  namespace: ops-stage
roleRef:
  kind: ClusterRole
  name: docker-registry-checker
  apiGroup: rbac.authorization.k8s.io
