apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-docker-registry-checker

# Note: ServiceAccount is namespaced (and user accounts are not)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-docker-registry-checker
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

# Note: ClusterRole is not namespaced

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-docker-registry-checker
subjects:
- kind: ServiceAccount
  name: sa-docker-registry-checker-dev
  namespace: ops-dev
roleRef:
  kind: ClusterRole
  name: cr-docker-registry-checker-dev
  apiGroup: rbac.authorization.k8s.io

