apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ops-staging
nameSuffix: "-staging"
commonLabels:
  app: docker-registry-checker-staging

resources:
- ../base

patches:
- path: fix-rb.yaml
- path: fix-deployment.yaml
  target:
    kind: Deployment


